# Generated by Django 3.0.7 on 2022-03-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmName', models.TextField()),
                ('mainURL', models.URLField()),
                ('dsCount', models.IntegerField()),
            ],
        ),
    ]
